### ISSUE TITLE
Data model v 1.0

### ISSUE THREAD

**Issue by r7perezyera** [FanchiniRudolf/MyHealthJournal#1]
User (a document in a collection of users)
   - Condition collection (contains Condition documents which points to:)
        - Entry collection (contains Entry documents)
   - Medicine collection (contains Medicine documents)
---
TODO: Create _Medicine_ class

:octocat:

**Comment by FanchiniRudolf** [comment]
>:c

**Comment by r7perezyera** [comment]
#### Final Data Model ✅ 
Already created in Firebase (Cloud Firestore), and in use for testing. 👍 

![IMG_30945F6956CD-1](https://user-images.githubusercontent.com/30813785/84106108-e3086200-a9df-11ea-9715-95976821b0a0.jpeg)
